import { examConfig } from '@/config/examConfig';
import { getSubject, getTopic } from '@/data/subjects';
import type { AnswerOption, Language, MockTest, Question } from '@/types/exam';

/**
 * Question-bank validation.
 *
 * Runs as a development-time guard (see `runDevValidation`) and as a CI script
 * (`npm run validate:questions`), so a malformed question is caught when it is
 * authored rather than when a candidate hits it mid-exam.
 */

export type IssueLevel = 'error' | 'warning';

export interface ValidationIssue {
  level: IssueLevel;
  message: string;
  questionId?: string;
  field?: string;
}

export interface ValidationReport {
  valid: boolean;
  checked: number;
  errors: ValidationIssue[];
  warnings: ValidationIssue[];
}

const VALID_OPTIONS: AnswerOption[] = ['A', 'B', 'C', 'D'];

const hasText = (value: string | undefined): boolean => typeof value === 'string' && value.trim().length > 0;

function emptyReport(): ValidationReport {
  return { valid: true, checked: 0, errors: [], warnings: [] };
}

function push(report: ValidationReport, issue: ValidationIssue): void {
  if (issue.level === 'error') {
    report.errors.push(issue);
    report.valid = false;
  } else {
    report.warnings.push(issue);
  }
}

/** Validates one question in isolation. */
export function validateQuestion(question: Question, report: ValidationReport): void {
  const id = question.id;
  const error = (message: string, field?: string): void =>
    push(report, { level: 'error', message, questionId: id, field });
  const warn = (message: string, field?: string): void =>
    push(report, { level: 'warning', message, questionId: id, field });

  if (!hasText(question.id)) {
    error('Question is missing an id.', 'id');
    return;
  }

  if (question.paper !== 'paper1' && question.paper !== 'paper2') {
    error(`Unknown paper "${String(question.paper)}".`, 'paper');
  }

  const subject = getSubject(question.subject);
  if (!subject) {
    error(`Unknown subject "${question.subject}". Add it to src/data/subjects.ts.`, 'subject');
  } else {
    if (subject.paper !== question.paper) {
      error(`Subject "${question.subject}" belongs to ${subject.paper}, not ${question.paper}.`, 'subject');
    }
    if (!getTopic(question.subject, question.topic)) {
      error(`Unknown topic "${question.topic}" for subject "${question.subject}".`, 'topic');
    }
  }

  // Question text: at least one language must be present.
  const questionLanguages = examConfig.languages.filter((language) => hasText(question.question[language]));
  if (questionLanguages.length === 0) {
    error('Question text is empty in every configured language.', 'question');
  } else {
    for (const language of examConfig.languages) {
      if (!hasText(question.question[language])) {
        warn(`Missing ${language} translation for the question text.`, 'question');
      }
    }
  }

  // Options.
  const optionTexts = new Map<string, AnswerOption[]>();
  for (const key of VALID_OPTIONS) {
    const option = question.options?.[key];
    if (!option) {
      error(`Option ${key} is missing.`, `options.${key}`);
      continue;
    }
    const available = examConfig.languages.filter((language) => hasText(option[language]));
    if (available.length === 0) {
      error(`Option ${key} has no text in any configured language.`, `options.${key}`);
      continue;
    }
    for (const language of examConfig.languages) {
      if (!hasText(option[language])) {
        warn(`Missing ${language} translation for option ${key}.`, `options.${key}`);
      }
    }
    for (const language of examConfig.languages) {
      const text = option[language]?.trim().toLowerCase();
      if (!text) continue;
      const signature = `${language}:${text}`;
      const owners = optionTexts.get(signature) ?? [];
      owners.push(key);
      optionTexts.set(signature, owners);
    }
  }

  for (const [signature, owners] of optionTexts) {
    if (owners.length > 1) {
      warn(`Options ${owners.join(', ')} are identical (${signature.split(':')[0]}).`, 'options');
    }
  }

  // Correct option.
  if (!VALID_OPTIONS.includes(question.correctOption)) {
    error(
      `correctOption must be one of A, B, C, D — received "${String(question.correctOption)}". ` +
        'E is reserved for "I do not know" and is generated by the UI.',
      'correctOption',
    );
  }

  // Explanation is optional but strongly recommended for the review screen.
  if (!question.explanation) {
    warn('No explanation provided; the review screen will show a placeholder.', 'explanation');
  } else {
    const explanationLanguages = examConfig.languages.filter((language) =>
      hasText(question.explanation?.[language]),
    );
    if (explanationLanguages.length === 0) {
      warn('Explanation object is present but empty.', 'explanation');
    }
  }
}

/** Validates a full mock test, including cross-question checks. */
export function validateMockTest(test: MockTest): ValidationReport {
  const report = emptyReport();

  if (!hasText(test.id)) {
    push(report, { level: 'error', message: 'Mock test is missing an id.' });
  }

  if (!Array.isArray(test.questions) || test.questions.length === 0) {
    push(report, { level: 'error', message: `Mock test "${test.id}" has an empty question bank.` });
    return report;
  }

  const seen = new Set<string>();
  for (const question of test.questions) {
    report.checked += 1;
    if (seen.has(question.id)) {
      push(report, {
        level: 'error',
        message: `Duplicate question id "${question.id}" in mock test "${test.id}".`,
        questionId: question.id,
      });
    }
    seen.add(question.id);
    validateQuestion(question, report);
  }

  const duration = test.durationMinutes ?? examConfig.durationMinutes;
  if (duration <= 0) {
    push(report, { level: 'error', message: `Mock test "${test.id}" has a non-positive duration.` });
  }

  return report;
}

export function validateMockTests(tests: MockTest[]): ValidationReport {
  const combined = emptyReport();
  const seenIds = new Set<string>();

  for (const test of tests) {
    if (seenIds.has(test.id)) {
      push(combined, { level: 'error', message: `Duplicate mock test id "${test.id}".` });
    }
    seenIds.add(test.id);

    const report = validateMockTest(test);
    combined.checked += report.checked;
    combined.errors.push(...report.errors);
    combined.warnings.push(...report.warnings);
  }

  combined.valid = combined.errors.length === 0;
  return combined;
}

/** Human-readable report used by the CLI script and the dev console. */
export function formatReport(report: ValidationReport): string {
  const lines: string[] = [
    `Checked ${report.checked} question(s): ${report.errors.length} error(s), ${report.warnings.length} warning(s).`,
  ];
  for (const issue of report.errors) {
    lines.push(`  ERROR   ${issue.questionId ?? '-'}${issue.field ? ` [${issue.field}]` : ''}: ${issue.message}`);
  }
  for (const issue of report.warnings) {
    lines.push(`  WARNING ${issue.questionId ?? '-'}${issue.field ? ` [${issue.field}]` : ''}: ${issue.message}`);
  }
  return lines.join('\n');
}

/** Languages a question can actually be rendered in. */
export function availableLanguages(question: Question): Language[] {
  return examConfig.languages.filter((language) => hasText(question.question[language]));
}
